language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: eSPXmspvAHwHP3mZIfWQ5yzbwBoebFVMbdBJt9C8Et9sbXBSTrRSHXGfzyNPkHwXVcIqA3Ivl1YmHMXxJtQmjNmuk1ppAFcDZ/1HrvaNfJfOtWQVt+pSriDWV9vPbyIAUVdbD+NCd6pZjEPdgff+ZeN8pq8P/qFgd17EE0qj9dpaYEq8vupnJ8gVDQb7H5EKL/akKN4ahj+WJdh0jyRJ4UtYztLYJYcD4Arle0ec5sCSUl8ytHfSh3lZ8432ZGZ0NcmL4UvWK+qIGqo2MF2dZRqW7gyNoUYEKaGZu7bfK44AoFPD8YIv/TqQpHFyj+KoNhMxlkV0J4Ms9hN8+94eCB7FW/pV6Fg1/P21BEwePThbBYzpFkgDnafbOgVm1y5vdNywg3VPugb3AgEJVK4RsdYLqQYEN5/uYhxVjcPkMJNh+9ZA3j78al9cJbtvnaSSHs2no6oquBpanvDuIxJTDS4slHbGvGnr5s7yBCyGIQACmuvoNIvC376lqMTkGEqYlRag86nDfUYAJTzFr6WNBOdgnWxv0isBquuH4DD9Tys1Bc0yOBej1sNndDaVnf2x3rBAIvU2Hv3lujiwVn6IDAeMiEpjwd1JoIEzQ0UrUgBiSz5FC6ekYGYyl2CazJbV6uIVJS0Lo8Aes3nTKGXEixUUM7XXDKQsCVQpG2TmVZA=
  app: arcane-dawn-34106
  on:
    repo: KennethJMiddleton/blog-api-2
